=== ONSdigital/eq-questionnaire-validator/schemas/questionnaire_v1.json
{
  "$id": "/questionnaire_v1.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "mime_type",
    "schema_version",
    "data_version",
    "survey_id",
    "title",
    "sections",
    "theme",
    "metadata",
    "language",
    "questionnaire_flow"
  ],
  "properties": {
    "language": {
      "enum": ["cy", "en", "eo", "ga"]
    },
    "messages": {
      "$ref": "common_definitions.json#/messages"
    },
    "mime_type": {
      "type": "string"
    },
    "schema_version": {
      "type": "string"
    },
    "data_version": {
      "enum": ["0.0.1", "0.0.3"]
    },
    "survey_id": {
      "type": "string",
      "description": "The ONS id of the survey derived from the inquiry code already in use for that survey.",
      "pattern": "^[0-9a-z]+$"
    },
    "session_timeout_in_seconds": {
      "description": "The amount of time in seconds before timing out a users session.",
      "type": "integer"
    },
    "title": {
      "$ref": "common_definitions.json#/non_empty_string"
    },
    "description": {
      "$ref": "common_definitions.json#/non_empty_string"
    },
    "theme": {
      "enum": [
        "business",
        "social",
        "default",
        "health",
        "northernireland",
        "dbt",
        "dbt-ni",
        "dbt-dsit",
        "dbt-dsit-ni",
        "orr",
        "desnz",
        "desnz-ni",
        "census",
        "census-nisra"
      ]
    },
    "legal_basis": {
      "$ref": "common_definitions.json#/non_empty_string"
    },
    "form_type": {
      "type": "string",
      "pattern": "^[0-9A-Za-z_]+$"
    },
    "region_code": {
      "type": "string",
      "pattern": "^GB-[A-Z]{3}$",
      "description": "An ISO 3166-2:GB region code"
    },
    "answer_codes": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "code": {
            "pattern": "^[a-zA-Z0-9._-]+$",
            "description": "User defined answer code for a matching answer id"
          },
          "answer_id": {
            "$ref": "common_definitions.json#/identifier",
            "description": "The `answer_id` this `code` mapping is for."
          },
          "answer_value": {
            "$ref": "common_definitions.json#/non_empty_string",
            "description": "Optional answer value for the given answer code. This should only used for answers that support `options`."
          }
        },
        "additionalProperties": false,
        "required": ["answer_id", "code"]
      }
    },
    "metadata": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "pattern": "^[a-zA-Z0-9-_]+$"
          },
          "type": {
            "type": "string",
            "enum": ["boolean", "date", "string", "uuid", "url"]
          },
          "min_length": {
            "type": "integer",
            "description": "The minimum length of a string field",
            "minimum": 1
          },
          "max_length": {
            "type": "integer",
            "description": "The maximum length of a string field",
            "minimum": 1
          },
          "length": {
            "type": "integer",
            "description": "The length of a string field must be equal to this",
            "minimum": 0
          },
          "optional": {
            "description": "Whether an error should be raised if this field is not provided.",
            "type": "boolean"
          }
        },
        "additionalProperties": false,
        "required": ["name", "type"]
      }
    },
    "variables": {
      "type": "object",
      "properties": {
        "period": {
          "$ref": "common_definitions.json#/non_empty_string"
        }
      }
    },
    "navigation": {
      "type": "object",
      "description": "Used in conjunction with routing to take user through a survey. ",
      "properties": {
        "visible": {
          "type": "boolean"
        }
      }
    },
    "questionnaire_flow": {
      "$ref": "questionnaire_flow/definitions.json#/flow"
    },
    "submission": {
      "type": "object",
      "properties": {
        "button": {
          "$ref": "common_definitions.json#/non_empty_string",
          "description": "The submit button text when the questionnaire is complete."
        },
        "guidance": {
          "$ref": "common_definitions.json#/non_empty_string",
          "description": "The guidance when the questionnaire is complete."
        },
        "title": {
          "$ref": "common_definitions.json#/non_empty_string",
          "description": "The main heading when the questionnaire is complete."
        },
        "warning": {
          "$ref": "common_definitions.json#/non_empty_string",
          "description": "The warning when the questionnaire is complete."
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "post_submission": {
      "type": "object",
      "properties": {
        "guidance": {
          "description": "Guidance displayed after the questionnaire is submitted.",
          "type": "object",
          "properties": {
            "contents": {
              "$ref": "common_definitions.json#/contents"
            }
          },
          "required": ["contents"],
          "additionalProperties": false
        },
        "confirmation_email": {
          "type": "boolean",
          "description": "A flag that is used to determine if an email confirmation is available on questionnaire completion"
        },
        "feedback": {
          "type": "boolean",
          "description": "A flag that is used to determine if a feedback is available on questionnaire completion"
        },
        "view_response": {
          "type": "boolean",
          "description": "A flag that is used to determine if the users response is viewable after submission"
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "individual_response": {
      "$ref": "individual_response/definitions.json#/individual_response"
    },
    "sections": {
      "type": "array",
      "minItems": 1,
      "items": {
        "additionalProperties": false,
        "type": "object",
        "properties": {
          "id": {
            "$ref": "common_definitions.json#/identifier"
          },
          "title": {
            "$ref": "common_definitions.json#/non_empty_string",
            "description": "Title used for the navigation container."
          },
          "title_from_answers": {
            "type": "array",
            "description": "Takes a list of answer ids. Title will be generated from answer values concatenated together with spaces."
          },
          "repeat": {
            "type": "object",
            "properties": {
              "for_list": {
                "$ref": "common_definitions.json#/non_empty_string"
              },
              "title": {
                "$ref": "string_interpolation/definitions.json#/string_with_placeholders"
              },
              "page_title": {
                "$ref": "common_definitions.json#/non_empty_string"
              }
            },
            "additionalProperties": false,
            "required": ["for_list", "title"]
          },
          "summary": {
            "type": "object",
            "properties": {
              "show_on_completion": {
                "type": "boolean",
                "description": "A boolean that is used to determine whether to show the section summary on completion of the section."
              },
              "collapsible": {
                "type": "boolean"
              },
              "items": {
                "type": "array",
                "minItems": 1,
                "items": {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string",
                      "enum": ["List"]
                    },
                    "for_list": {
                      "$ref": "common_definitions.json#/non_empty_string"
                    },
                    "title": {
                      "$ref": "string_interpolation/definitions.json#/string_with_placeholders"
                    },
                    "add_link_text": {
                      "$ref": "common_definitions.json#/non_empty_string"
                    },
                    "empty_list_text": {
                      "$ref": "common_definitions.json#/non_empty_string"
                    },
                    "related_answers": {
                      "type": "array",
                      "minItems": 1,
                      "uniqueItems": true,
                      "items": {
                        "$ref": "value_sources.json#/answer_value_source"
                      },
                      "description": "Value sources of answers to be displayed on the list summary, excluding the answer used for the item title"
                    },
                    "item_anchor_answer_id": {
                      "$ref": "common_definitions.json#/identifier",
                      "description": "The main answer_id for the item title used as anchor in summary links"
                    },
                    "item_label": {
                      "$ref": "string_interpolation/definitions.json#/string_with_placeholders",
                      "description": "The accompanying label for the item title on list summary",
                      "examples": ["Name of company", "Full name"]
                    }
                  },
                  "additionalProperties": false
                }
              },
              "title": {
                "$ref": "string_interpolation/definitions.json#/string_with_placeholders"
              },
              "page_title": {
                "$ref": "common_definitions.json#/non_empty_string"
              },
              "show_non_item_answers": {
                "type": "boolean",
                "description": "When true, non list collector answers will be displayed on the section summary. When false, a list summary is used where only list items are displayed."
              }
            },
            "if": {
              "properties": {
                "show_non_item_answers": {
                  "not": {
                    "const": true
                  }
                }
              }
            },
            "then": {
              "required": ["show_on_completion"]
            },
            "else": {
              "required": ["items", "show_on_completion"]
            },
            "additionalProperties": false
          },
          "show_on_hub": {
            "type": "boolean",
            "description": "When the hub is enabled, this will determine if the section appears. Default is true"
          },
          "groups": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "$ref": "common_definitions.json#/identifier"
                },
                "title": {
                  "$ref": "common_definitions.json#/non_empty_string"
                },
                "hide_in_navigation": {
                  "type": "boolean"
                },
                "skip_conditions": {
                  "$ref": "common_definitions.json#/skip_conditions"
                },
                "routing_rules": {
                  "$ref": "common_definitions.json#/routing_rules"
                },
                "blocks": {
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "oneOf": [
                      {
                        "$ref": "blocks/answer_summary.json#/block"
                      },
                      {
                        "$ref": "blocks/calculated_summary.json#/block"
                      },
                      {
                        "$ref": "blocks/grand_calculated_summary.json#/block"
                      },
                      {
                        "$ref": "blocks/confirmation_question.json#/block"
                      },
                      {
                        "$ref": "blocks/interstitial.json#/block"
                      },
                      {
                        "$ref": "blocks/introduction.json#/block"
                      },
                      {
                        "$ref": "blocks/list_collector.json#/block"
                      },
                      {
                        "$ref": "blocks/list_collector_driving_question.json#/block"
                      },
                      {
                        "$ref": "blocks/primary_person_list_collector.json#/block"
                      },
                      {
                        "$ref": "blocks/question.json#/block"
                      },
                      {
                        "$ref": "blocks/relationship_collector.json#/block"
                      }
                    ]
                  }
                }
              },
              "additionalProperties": false,
              "required": ["id", "blocks"]
            }
          },
          "enabled": {
            "$ref": "common_definitions.json#/section_enabled"
          }
        },
        "required": ["id", "groups"]
      }
    },
    "preview_questions": {
      "type": "boolean",
      "description": "A flag that is used to determine if the questions can be previewed before the questionnaire start"
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "questionnaire_flow": {
            "properties": {
              "type": {
                "const": "Hub"
              }
            }
          }
        }
      },
      "then": {
        "properties": {
          "sections": {
            "items": {
              "required": ["title"]
            }
          }
        }
      }
    }
  ],
  "additionalProperties": false
}

=== ONSdigital/eq-questionnaire-validator/tests/schemas/valid/test_question_validation_messages.json
{
  "mime_type": "application/json/ons/eq",
  "language": "en",
  "schema_version": "0.0.1",
  "data_version": "0.0.3",
  "survey_id": "0",
  "title": "Question Validation Test",
  "theme": "default",
  "description": "A questionnaire to test use of the question title in validation",
  "metadata": [
    {
      "name": "user_id",
      "type": "string"
    },
    {
      "name": "period_id",
      "type": "string"
    },
    {
      "name": "ru_name",
      "type": "string"
    }
  ],
  "questionnaire_flow": {
    "type": "Linear",
    "options": {
      "summary": {
        "collapsible": false
      }
    }
  },
  "sections": [
    {
      "id": "mutually-exclusive-checkbox-section",
      "groups": [
        {
          "blocks": [
            {
              "type": "Question",
              "id": "total-block",
              "question": {
                "id": "total-question",
                "title": "Total",
                "description": [
                  "Enter a number to breakdown in subsequent questions and calculated summary."
                ],
                "type": "General",
                "answers": [
                  {
                    "id": "total-answer",
                    "label": "Total",
                    "mandatory": true,
                    "type": "Number",
                    "decimal_places": 2,
                    "minimum": {
                      "value": 0,
                      "exclusive": true
                    }
                  }
                ]
              }
            },
            {
              "type": "Question",
              "id": "date-block",
              "question": {
                "answers": [
                  {
                    "id": "date-range-from-answer",
                    "label": "Period from",
                    "mandatory": true,
                    "type": "Date"
                  },
                  {
                    "id": "date-range-to-answer",
                    "label": "Period to",
                    "mandatory": true,
                    "type": "Date"
                  }
                ],
                "id": "date-range-question",
                "title": "Date range",
                "warning": "The period to date must be after the period from date",
                "type": "DateRange",
                "validation": {
                  "messages": {
                    "INVALID_DATE_RANGE": "The date range specified is invalid"
                  }
                }
              }
            }
          ],
          "id": "dates"
        },
        {
          "id": "calculated-question-group",
          "title": "Calculated Question Group",
          "blocks": [
            {
              "type": "Question",
              "id": "breakdown-block",
              "question": {
                "id": "breakdown-question",
                "title": "Breakdown",
                "type": "Calculated",
                "calculations": [
                  {
                    "calculation_type": "sum",
                    "answer_id": "total-answer",
                    "answers_to_calculate": ["breakdown-1", "breakdown-2"],
                    "conditions": ["less than"]
                  }
                ],
                "answers": [
                  {
                    "id": "breakdown-1",
                    "label": "Breakdown 1",
                    "mandatory": false,
                    "decimal_places": 2,
                    "type": "Currency",
                    "currency": "GBP"
                  },
                  {
                    "id": "breakdown-2",
                    "label": "Breakdown 2",
                    "mandatory": false,
                    "decimal_places": 2,
                    "type": "Currency",
                    "currency": "GBP"
                  }
                ],
                "validation": {
                  "messages": {
                    "TOTAL_SUM_NOT_LESS_THAN": "Enter answers that add up to or are less than total answer"
                  }
                }
              }
            }
          ]
        },
        {
          "id": "mutually-exclusive-mandatory-group",
          "title": "Mutually Exclusive Group",
          "blocks": [
            {
              "type": "Question",
              "id": "mutually-exclusive-checkbox",
              "question": {
                "id": "mutually-exclusive-checkbox-question",
                "type": "MutuallyExclusive",
                "title": "Were you a resident at any of the following addresses?",
                "mandatory": true,
                "answers": [
                  {
                    "id": "checkbox-answer",
                    "label": "Select answer",
                    "type": "Checkbox",
                    "mandatory": false,
                    "options": [
                      {
                        "label": "7 Evelyn Street, Barry",
                        "value": "7 Evelyn Street, Barry"
                      },
                      {
                        "label": "251 Argae Lane, Barry",
                        "value": "251 Argae Lane, Barry"
                      }
                    ]
                  },
                  {
                    "id": "checkbox-exclusive-answer",
                    "mandatory": false,
                    "type": "Checkbox",
                    "options": [
                      {
                        "label": "I prefer not to say",
                        "description": "Some description",
                        "value": "I prefer not to say"
                      }
                    ]
                  }
                ],
                "validation": {
                  "messages": {
                    "MANDATORY_QUESTION": "Select an answer to continue"
                  }
                }
              }
            }
          ]
        }
      ]
    }
  ]
}

=== ONSdigital/eq-questionnaire-validator/tests/schemas/valid/test_section_enabled.json
{
  "mime_type": "application/json/ons/eq",
  "language": "en",
  "schema_version": "0.0.1",
  "data_version": "0.0.3",
  "survey_id": "0",
  "title": "Other input fields",
  "theme": "default",
  "description": "A questionnaire to demo checkbox field Other input.",
  "messages": {
    "NUMBER_TOO_LARGE": "Number is too large",
    "NUMBER_TOO_SMALL": "Number cannot be less than zero",
    "INVALID_NUMBER": "Please enter an integer"
  },
  "metadata": [
    {
      "name": "user_id",
      "type": "string"
    },
    {
      "name": "period_id",
      "type": "string"
    },
    {
      "name": "ru_name",
      "type": "string"
    }
  ],
  "questionnaire_flow": {
    "type": "Hub",
    "options": {
      "required_completed_sections": ["default-section"]
    }
  },
  "sections": [
    {
      "id": "default-section",
      "groups": [
        {
          "blocks": [
            {
              "type": "Question",
              "id": "mandatory-checkbox",
              "question": {
                "answers": [
                  {
                    "id": "mandatory-checkbox-answer",
                    "label": "Label",
                    "mandatory": true,
                    "options": [
                      {
                        "label": "Yes",
                        "value": "Yes"
                      },
                      {
                        "label": "No",
                        "value": "No"
                      }
                    ],
                    "type": "Checkbox",
                    "validation": {
                      "messages": {}
                    }
                  }
                ],
                "id": "mandatory-checkbox-question",
                "title": "Should the second section be enabled?",
                "type": "General"
              }
            }
          ],
          "id": "checkboxes"
        }
      ]
    },
    {
      "id": "optionally-enabled-section",
      "enabled": [
        {
          "when": [
            {
              "id": "mandatory-checkbox-answer",
              "condition": "contains any",
              "values": ["Yes"]
            }
          ]
        }
      ],
      "groups": [
        {
          "blocks": [
            {
              "type": "Question",
              "id": "non-mandatory-checkbox",
              "question": {
                "answers": [
                  {
                    "id": "non-mandatory-checkbox-answer",
                    "label": "Label",
                    "mandatory": true,
                    "options": [
                      {
                        "label": "Yes",
                        "value": "Yes"
                      },
                      {
                        "label": "No",
                        "value": "No"
                      }
                    ],
                    "type": "Checkbox",
                    "validation": {
                      "messages": {}
                    }
                  }
                ],
                "id": "non-mandatory-checkbox-question",
                "title": "Was this section shown?",
                "type": "General"
              }
            }
          ],
          "id": "second-section-checkboxes"
        }
      ]
    }
  ]
}

=== ONSdigital/eq-questionnaire-validator/tests/schemas/valid/test_introduction_with_guidance.json
{
  "mime_type": "application/json/ons/eq",
  "language": "en",
  "schema_version": "0.0.1",
  "data_version": "0.0.3",
  "survey_id": "144",
  "theme": "default",
  "title": "Test introduction",
  "legal_basis": "Notice is given under section 999 of the Test Act 2000",
  "metadata": [
    {
      "name": "user_id",
      "type": "string"
    },
    {
      "name": "period_id",
      "type": "string"
    },
    {
      "name": "ru_name",
      "type": "string"
    },
    {
      "name": "ru_ref",
      "type": "string"
    },
    {
      "name": "trad_as",
      "type": "string",
      "optional": true
    }
  ],
  "questionnaire_flow": {
    "type": "Linear",
    "options": {}
  },
  "sections": [
    {
      "id": "introduction-section",
      "title": "Introduction",
      "groups": [
        {
          "id": "introduction-group",
          "title": "General Business Information",
          "blocks": [
            {
              "id": "introduction",
              "type": "Introduction",
              "primary_content": [
                {
                  "id": "business-details",
                  "title": "You are completing this for ESSENTIAL ENTERPRISE LTD.",
                  "contents": [
                    {
                      "guidance": {
                        "contents": [
                          {
                            "title": "Coronavirus (COVID-19) guidance",
                            "description": "<strong>Explain your figures</strong> in the comment section to minimise us contacting you and to help us tell an industry story"
                          }
                        ]
                      }
                    }
                  ]
                }
              ]
            },
            {
              "type": "Interstitial",
              "id": "general-business-information-completed",
              "content": {
                "title": "Section complete",
                "contents": [
                  {
                    "description": "<p>You have successfully completed this section</p>"
                  }
                ]
              }
            }
          ]
        }
      ]
    }
  ]
}

=== ONSdigital/eq-questionnaire-validator/tests/schemas/valid/test_text_field_suggestions.json
{
  "mime_type": "application/json/ons/eq",
  "language": "en",
  "schema_version": "0.0.1",
  "data_version": "0.0.3",
  "survey_id": "001",
  "title": "Textfield Suggestions",
  "theme": "default",
  "description": "A questionnaire to test textfield suggestions",
  "metadata": [
    {
      "name": "user_id",
      "type": "string"
    },
    {
      "name": "period_id",
      "type": "string"
    },
    {
      "name": "ru_name",
      "type": "string"
    }
  ],
  "questionnaire_flow": {
    "type": "Linear",
    "options": {
      "summary": {
        "collapsible": false
      }
    }
  },
  "sections": [
    {
      "id": "default-section",
      "groups": [
        {
          "blocks": [
            {
              "type": "Question",
              "id": "country-block",
              "question": {
                "answers": [
                  {
                    "id": "country-answer",
                    "label": "What is your country of birth?",
                    "mandatory": false,
                    "suggestions": {
                      "url": "/json/countries"
                    },
                    "type": "TextField"
                  }
                ],
                "id": "country-of-birth-question",
                "title": "Title",
                "type": "General"
              }
            }
          ],
          "id": "group"
        }
      ]
    }
  ]
}

=== ONSdigital/eq-questionnaire-validator/tests/schemas/valid/test_calculations_with_numeric_value.json
{
  "mime_type": "application/json/ons/eq",
  "language": "en",
  "schema_version": "0.0.1",
  "data_version": "0.0.3",
  "survey_id": "0",
  "title": "Calculated question with a number value test survey",
  "theme": "default",
  "description": "A survey that tests validation against a calculated question with a valid number value",
  "metadata": [
    {
      "name": "user_id",
      "type": "string"
    },
    {
      "name": "period_id",
      "type": "string"
    },
    {
      "name": "ru_name",
      "type": "string"
    }
  ],
  "questionnaire_flow": {
    "type": "Linear",
    "options": {
      "summary": {
        "collapsible": false
      }
    }
  },
  "sections": [
    {
      "id": "default-section",
      "groups": [
        {
          "id": "group",
          "title": "Validate sum against value, calculated summary source",
          "blocks": [
            {
              "type": "Question",
              "id": "breakdown-block",
              "question": {
                "id": "breakdown-question",
                "title": "Breakdown validated against a number value",
                "description": [
                  "This is a breakdown of the total from a number value."
                ],
                "type": "Calculated",
                "calculations": [
                  {
                    "calculation_type": "sum",
                    "value": 100,
                    "answers_to_calculate": ["breakdown-1", "breakdown-2"],
                    "conditions": ["equals"]
                  }
                ],
                "answers": [
                  {
                    "id": "breakdown-1",
                    "label": "Breakdown 1",
                    "mandatory": false,
                    "decimal_places": 2,
                    "type": "Number"
                  },
                  {
                    "id": "breakdown-2",
                    "label": "Breakdown 2",
                    "mandatory": false,
                    "decimal_places": 2,
                    "type": "Number"
                  }
                ]
              }
            }
          ]
        }
      ]
    }
  ]
}
